"""add_assigned_by_parent_id_to_assessments

Revision ID: 153d146a2a10
Revises: 0f01c071ef73
Create Date: <DATETIME>

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '153d146a2a10'
down_revision: Union[str, None] = '0f01c071ef73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Assessments', sa.Column('assigned_by_parent_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(
        'fk_assessments_assigned_by_parent', 'Assessments',
        'Users', ['assigned_by_parent_id'], ['user_id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_assessments_assigned_by_parent', 'Assessments', type_='foreignkey')
    op.drop_column('Assessments', 'assigned_by_parent_id')
    # ### end Alembic commands ###
